regrid:
    ocean_static_path: "TEST_DATA/mom_input/ocean_static.nc"
    mom_lat_var: "geolat"
    mom_lon_var: "geolon"
    sst_grid_path: "TEST_DATA/OSTIA_jan2015/20150101-UKMO-L4HRfnd-GLOB-v01-fv02-OSTIA.nc"
    sst_lat_var: "lat"
    sst_lon_var: "lon"
    regridder_file_path: "TEST_DATA/wts/wts_ostia_to_mom_p25_v2.nc"

fill:
    restore_template_path:  "fix/T_restore_file.yaml"
    ocean_static_path: "TEST_DATA/mom_input/ocean_static.nc"
    ocean_hgrid_path: "TEST_DATA/mom_input/ocean_hgrid.nc"
    mom_lat_var: "geolat"
    mom_lon_var: "geolon"
    mom_wet_var: "wet"
    sst_lat_var: "lat"
    sst_lon_var: "lon"
    sst_sst_var: "analysed_sst"
    sst_var_renamed: "SST"
    new_time_units: "hours since 1900-01-01 00:00:00" # need to be the same as the restore file template
    regridder_file_path: "TEST_DATA/wts/wts_ostia_to_mom_p25_v2.nc"
