regrid:
    ocean_static_path: "TEST_DATA/mom_input/ocean_static.nc"
    mom_lat_var: "geolat"
    mom_lon_var: "geolon"
    woa_grid_path: "../../test_data/woa18_decav_s01_04.nc"
    woa_lat_var: "lat"
    woa_lon_var: "lon"
    regridder_file_path: "TEST_DATA/wts/wts_woa_to_mom_p25_v2.nc"

remap:
    restore_template_path:  "fix/S_restore_file.yaml"
    ocean_static_path: "TEST_DATA/mom_input/ocean_static.nc"
    ocean_hgrid_path: "TEST_DATA/mom_input/ocean_hgrid.nc"
    mom_lat_var: "geolat"
    mom_lon_var: "geolon"
    mom_wet_var: "wet"
    woa_grid_path: "filled_SALT_s01_e12.nc"
    woa_lat_var: "lat"
    woa_lon_var: "lon"
    woa_var: "SALT"
    woa_var_renamed: "SALT"
    new_time_units: "hours since 1900-01-01 00:00:00" # need to be the same as the restore file template
    regridder_file_path: "TEST_DATA/wts/wts_woa_to_mom_p25_v2.nc"
